### ISSUE TITLE
Emoji leads to weird slug

### ISSUE THREAD

**Issue by MoOx** [ben-eb/remark-autolink-headings#30]
![screen shot 2016-08-30 at 12 45 47](https://cloud.githubusercontent.com/assets/157534/18086339/b28e3ad8-6eaf-11e6-9f94-a3b47bc0dcc3.png)

Watch carfully the hovered link (it looks good), but when clicking, I got a weird URL. I assume that the emoji is still here, but hidden.

It seems that remark-slug is ok as you can see in the HTML. Ref https://github.com/wooorm/remark-slug/issues/2

**Comment by wooorm** [comment]
The bug, as I [found out](https://github.com/wooorm/remark-slug/issues/2#issuecomment-243405034), is caused because there’s a VARIANT SELECTOR-16 just after the emoji.

GitHub also includes it: https://github.com/MoOx/phenomic/blob/671a0cf596f184e2d1c30b77e219f4711e5e25ce/docs/content/docs/usage/gh-pages.md#%EF%B8%8F-warning-for-githubio-domain

As you can see from that link, GH URL encodes the link. Which I think should be done too\*.

```js
callback('#' + encodeURIComponent(data.htmlAttributes.id));
```

...which can be added [here](https://github.com/ben-eb/remark-autolink-headings/blob/ca40ea3cdf24ab05c0d18d08e7b3863344e0ff36/src/index.js#L18)

\* I think this should be done here, but maybe in the HAST-related tools instead. Unsure.

**Comment by ben-eb** [comment]
https://github.com/ben-eb/remark-autolink-headings/commit/54434ffc75b3338fdb8127151ab8b8f15899a08c look good to you guys?

**Comment by wooorm** [comment]
@ben-eb Yup!

**Comment by ben-eb** [comment]
Problem is that this test still passes if I change the line back to how it was originally. 😐

**Comment by wooorm** [comment]
@ben-eb The tests fail because, I believe, the fixture uses `&#xFE0F;` and other entities, but you can just use the literal characters (they don’t have to be encoded)

> Problem is that this test still passes if I change the line back to how it was originally. 😐

How do you mean?

**Comment by ben-eb** [comment]
Tried a node modules re-install and now my local environment reports the same as Travis, so I don't know what that was about! I fixed the fixture anyway now.

It means that the test still passes regardless of me changing this line. I don't know why this is the case but it would seem to indicate that me changing the line didn't do anything...

**Comment by wooorm** [comment]
I no longer think this is a bug, neither in remark-slug, nor in remark-autolink-headings. Rather, it’s behaviour as expected. Upon re-reading your question, @MoOx, it seems you were wondering where the `#%EF...` in the URL was coming from. Well: it’s because you have a VARIANT SELECTOR character in there, and it shows up in the HTML. As expected.

@ben-eb IMO this can be closed.

@MoOx I’m not sure why that variant selector is in there, either remove it if you want a pretty url, or keep it in there and deal with the URL being like this!

**Comment by ben-eb** [comment]
@wooorm It might be worth investigating into an option to strip emoji from the generated slug, which could work around this issue. That's an issue for remark-slug though so I'm going to go ahead and close this. 😄

**Comment by wooorm** [comment]
> Strip emoji from the generated slug

Well, the emoji themselves are already stripped, using the same mechanism as on GitHub and npm. If we deviate from this mechanism, it’ll break links across those vendors too.

I did some more digging, and found [this article](http://mts.io/2015/04/21/unicode-symbol-render-text-emoji/) to explain a bit more.

I could see how the VS16/VS15 should possible be removed, but as GH doesn’t do it I don’t think we should do it either.

**Comment by ben-eb** [comment]
OK, fair enough. 👍

**Comment by MoOx** [comment]
I just used the macOS native emoji picker to add this warning emoji. Nothing more... :'(

**Comment by wooorm** [comment]
Aww, haha :')
